{
 "title": "Forno de Pré-Oxidação",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Temperaturas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura Zona 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z1_mes as temperatura_medida\r\nFROM\r\n  preox_mes\r\nORDER BY id DESC\r\nLIMIT 17000;"
    },
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z1_con as temperatura_target\r\nFROM\r\n  preox_con\r\nORDER BY id DESC\r\nLIMIT 17000;"
    }
   ]
  },
  {
   "title": "Temperatura Zona 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT preox_temp_z1_mes as temperatura_medida \r\nFROM preox_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
    },
    {
     "rawSql": "SELECT preox_temp_z1_con as temperatura_target \r\nFROM preox_con\r\nORDER BY id DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperatura Zona 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z2_mes as temperatura_medida\r\nFROM\r\n  preox_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
    },
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z2_con as temperatura_target\r\nFROM\r\n  preox_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
    }
   ]
  },
  {
   "title": "Temperatura Zona 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT preox_temp_z2_mes as temperatura_medida \r\nFROM preox_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
    },
    {
     "rawSql": "SELECT carbo_temp_z2_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperatura Zona 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z3_mes as temperatura_medida\r\nFROM\r\n  preox_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
    },
    {
     "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  preox_temp_z3_con as temperatura_target\r\nFROM\r\n  preox_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
    }
   ]
  },
  {
   "title": "Temperatura Zona 3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT preox_temp_z3_mes as temperatura_medida \r\nFROM preox_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
    },
    {
     "rawSql": "SELECT carbo_temp_z3_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}