{
 "title": "Forno carbonitruração",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperaturas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatura Zona 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z1_mes as temperatura_medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\nLIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z1_con as temperatura_target\r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 1",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT carbo_temp_z1_mes as temperatura_medida \r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT carbo_temp_z1_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z2_mes as temperatura_medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z2_con as temperatura_target\r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 2",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT carbo_temp_z2_mes as temperatura_medida \r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT carbo_temp_z2_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z3_mes as temperatura_medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z3_con as temperatura_target\r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 3",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT carbo_temp_z3_mes as temperatura_medida \r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT carbo_temp_z3_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z4_mes as temperatura_medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\nLIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z4_con as temperatura_target\r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 4",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT carbo_temp_z4_mes as temperatura_medida \r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT carbo_temp_z4_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z5_mes as temperatura_medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  carbo_temp_z5_con as temperatura_target\r\nFROM\r\n  carbo_con\r\nORDER BY time DESC;"
      }
     ]
    },
    {
     "title": "Temperatura Zona 5",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT carbo_temp_z5_mes as temperatura_medida \r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT carbo_temp_z5_con as temperatura_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Gases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caudal de Azoto (N2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  azoto_n2_mes as medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  azoto_n2_con as target \r\nFROM\r\n  carbo_con\r\nORDER BY time DESC;"
      }
     ]
    },
    {
     "title": "Caudal de Azoto (N2)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT azoto_n2_mes as Fluxo_medido\r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT azoto_n2_con as Fluxo_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Caudal de Metanol (N2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  metanol_ch3oh_mes as medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  metanol_ch3oh_con as target \r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Caudal de Metanol (N2)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT metanol_ch3oh_mes as Fluxo_medido\r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT metanol_ch3oh_con as Fluxo_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Caudal de Gás Natural (CH4)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  gas_ch4_mes as medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  gas_ch4_con as target \r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Caudal de gás Natural (CH4)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT gas_ch4_mes as Fluxo_medido\r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT gas_ch4_con as Fluxo_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Caudal de Amoniaco (NH3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  amoniaco_nh3_mes as medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      },
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  amoniaco_nh3_con as target \r\nFROM\r\n  carbo_con\r\nORDER BY time DESC\r\nLIMIT 17000;"
      }
     ]
    },
    {
     "title": "Caudal de Amoniaco (NH3)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "litreh" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT amoniaco_nh3_mes as Fluxo_medido\r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      },
      {
       "rawSql": "SELECT amoniaco_nh3_con as Fluxo_target \r\nFROM carbo_con\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Percentagem de Carbono (%C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  (\"date\" + \"time\") as time,\r\n  c_mes as medida\r\nFROM\r\n  carbo_mes\r\nORDER BY\r\n  time DESC\r\n  LIMIT 17000;"
      }
     ]
    },
    {
     "title": "Caudal de Amoniaco (NH3)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT c_mes as Fluxo_medido\r\nFROM carbo_mes\r\nORDER BY id DESC\r\nLIMIT 1;"
      }
     ]
    }
   ]
  }
 ]
}