version: "3"

services:

  postgres:
    build: ./sql
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=fornocontinuo
    ports:
      - "5432:5432"

  opcua-client:
    build: ./simple_opcua_docker
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  grafana:
      image: grafana/grafana-enterprise
      ports:
        - 8069:3000
      environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
      depends_on:
        - postgres